In [4]:
import pandas as pd
df = pd.read_csv("Subset_Hockey_Data.csv",header = 0)
df.head()

,homeTeamCode,awayTeamCode,game_id,time,timeUntilNextEvent,period,team,SOG DIF,stdev,event,...,Goal Diff,homeEmptyNet,awayEmptyNet,homeSkatersOnIce,awaySkatersOnIce,Manpower Diff,isHomeTeam,shotWasOnGoal,teamCode,isPenalty
0,MTL,TOR,20001,0,0,1,NaN,0,0,GAMESTART,...,0,0,0,5,5,0,0,0,NaN,0
1,MTL,TOR,20001,74,74,1,AWAY,-1,0,MISS,...,0,0,0,5,5,0,0,0,TOR,0
2,MTL,TOR,20001,383,309,1,HOME,PENALTY,0,PENALTYSTART,...,0,0,0,4,5,-1,1,0,MTL,1
3,MTL,TOR,20001,396,13,1,AWAY,0,0,SHOT,...,0,0,0,4,5,-1,0,1,TOR,0
4,MTL,TOR,20001,438,42,1,HOME,PENALTY,0,PENALTYSTART,...,0,0,0,3,5,-2,1,0,MTL,1